source 'https://rubygems.org'

# GitHub Pages compatible gems
gem 'github-pages', group: :jekyll_plugins

# Jekyll plugins
group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-redirect-from'
  gem 'jekyll-mentions'
  gem 'jekyll-relative-links'
  gem 'jekyll-optional-front-matter'
  gem 'jekyll-readme-index'
  gem 'jekyll-default-layout'
  gem 'jekyll-titles-from-headings'
end

# Development dependencies
group :development do
  gem 'webrick', '~> 1.7'
  gem 'html-proofer', '~> 3.18'
end

# Windows and JRuby dependencies
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '~> 1.2'
  gem 'tzinfo-data'
end

# Performance-booster for watching directories on Windows
gem 'wdm', '~> 0.1.1', :platforms => [:mingw, :x64_mingw, :mswin] 